name: Create changelog commit
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: version
        run: ./gradlew
      - name: changelog
        run: ./gradlew generateGitChangelog
      - name: commit
#        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
#      - name: tag
        run: |
          git config user.email "you@example.com"
          git config user.name "github_actions"
          git add .
          git commit -m "release"
          git tag 0.0.9
          git push --follow-tags
#        with:
#          default_author: github_actions
