name: Create changelog commit
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Do Tag
        run: |
          git config user.email "you@example.com"
          git config user.name "github_actions"
          OUTPUT=$(./gradlew -q changelogVersion)
          echo $OUTPUT
          git tag "$OUTPUT"
          ./gradlew generateGitChangelog
          git tag -d "$OUTPUT"
          git add CHANGELOG.md gradle.properties 
          git commit -m "chore(release): $OUTPUT"
          git tag "$OUTPUT"
          git push --tags
          
          

#        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
#      - name: tag
#        with:
#          default_author: github_actions
